name = "DocumenterGlossip"
uuid = "d2b931d4-abbd-456c-a907-c3513416760c"
authors = ["knottyanyon"]
version = "0.1.0"

[deps]
Glossaries = "8f48dd54-e453-4cdc-9500-53b96149560b"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
